# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onguser',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='onguser',
            name='user',
            field=models.OneToOneField(default="", on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
