# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_auto_20171023_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
